name: maltilabeler-env
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - _libavif_api=1.3.0
  - aom=3.9.1
  - blas=1.0
  - brotli-python=1.1.0
  - bzip2=1.0.8
  - ca-certificates=2025.10.5
  - cairo=1.18.0
  - certifi=2025.10.5
  - cffi=2.0.0
  - charset-normalizer=3.4.3
  - cpuonly=2.0
  - dav1d=1.2.1
  - double-conversion=3.3.1
  - ffmpeg=6.1.1
  - filelock=3.19.1
  - font-ttf-dejavu-sans-mono=2.37
  - font-ttf-inconsolata=3.000
  - font-ttf-source-code-pro=2.038
  - font-ttf-ubuntu=0.83
  - fontconfig=2.15.0
  - fonts-conda-ecosystem=1
  - fonts-conda-forge=1
  - freeglut=3.2.2
  - freetype=2.14.1
  - fribidi=1.0.16
  - gdk-pixbuf=2.42.12
  - git-lfs=3.7.1
  - glib=2.80.2
  - glib-tools=2.80.2
  - glslang=15.4.0
  - graphite2=1.3.14
  - gst-plugins-base=1.24.5
  - gstreamer=1.24.5
  - h2=4.3.0
  - harfbuzz=10.2.0
  - hdf5=1.14.3
  - hpack=4.1.0
  - hyperframe=6.1.0
  - icu=73.2
  - idna=3.10
  - imath=3.1.12
  - intel-openmp=2025.2.0
  - jasper=4.2.8
  - jinja2=3.1.6
  - khronos-opencl-icd-loader=2024.10.24
  - krb5=1.21.3
  - lame=3.100
  - lcms2=2.16
  - lerc=4.0.0
  - libabseil=20240116.2
  - libaec=1.1.4
  - libasprintf=0.22.5
  - libavif16=1.3.0
  - libblas=3.9.0
  - libbrotlicommon=1.1.0
  - libbrotlidec=1.1.0
  - libbrotlienc=1.1.0
  - libcblas=3.9.0
  - libclang13=21.1.2
  - libcurl=8.14.1
  - libdeflate=1.21
  - libexpat=2.7.1
  - libffi=3.4.6
  - libfreetype=2.14.1
  - libfreetype6=2.14.1
  - libgettextpo=0.22.5
  - libglib=2.80.2
  - libhwloc=2.12.1
  - libhwy=1.3.0
  - libiconv=1.18
  - libintl=0.22.5
  - libintl-devel=0.22.5
  - libjpeg-turbo=3.1.0
  - libjxl=0.11.1
  - liblapack=3.9.0
  - liblapacke=3.9.0
  - liblzma=5.8.1
  - liblzma-devel=5.8.1
  - libogg=1.3.5
  - libopencv=4.10.0
  - libopenvino=2024.2.0
  - libopenvino-auto-batch-plugin=2024.2.0
  - libopenvino-auto-plugin=2024.2.0
  - libopenvino-hetero-plugin=2024.2.0
  - libopenvino-intel-cpu-plugin=2024.2.0
  - libopenvino-intel-gpu-plugin=2024.2.0
  - libopenvino-ir-frontend=2024.2.0
  - libopenvino-onnx-frontend=2024.2.0
  - libopenvino-paddle-frontend=2024.2.0
  - libopenvino-pytorch-frontend=2024.2.0
  - libopenvino-tensorflow-frontend=2024.2.0
  - libopenvino-tensorflow-lite-frontend=2024.2.0
  - libopus=1.5.2
  - libpng=1.6.50
  - libpq=12.15
  - libprotobuf=4.25.3
  - librsvg=2.58.1
  - libsqlite=3.50.4
  - libssh2=1.11.1
  - libtheora=1.1.1
  - libtiff=4.6.0
  - libusb=1.0.29
  - libuv=1.51.0
  - libvorbis=1.3.7
  - libvulkan-loader=1.4.313.0
  - libwebp=1.6.0
  - libwebp-base=1.6.0
  - libxcb=1.16
  - libxml2=2.13.8
  - libzlib=1.3.1
  - m2w64-gcc-libgfortran=5.3.0
  - m2w64-gcc-libs=5.3.0
  - m2w64-gcc-libs-core=5.3.0
  - m2w64-gmp=6.1.0
  - m2w64-libwinpthread-git=5.0.0.4634.697f757
  - markupsafe=3.0.3
  - mkl=2023.1.0
  - mpmath=1.3.0
  - msys2-conda-epoch=20160418
  - networkx=3.5
  - numpy=2.3.3
  - opencl-headers=2025.06.13
  - opencv=4.10.0
  - openexr=3.2.2
  - openh264=2.6.0
  - openjpeg=2.5.2
  - openssl=3.5.4
  - packaging=25.0
  - pandas=2.3.2
  - pango=1.54.0
  - pcre2=10.43
  - pillow=10.4.0
  - pip=25.2
  - pixman=0.46.4
  - ply=3.11
  - pthread-stubs=0.4
  - pugixml=1.14
  - py-opencv=4.10.0
  - pycparser=2.22
  - pyqt=6.7.1
  - pyqt6-sip=13.9.1
  - pysocks=1.7.1
  - python=3.11.13
  - python-dateutil=2.9.0.post0
  - python-tzdata=2025.2
  - python_abi=3.11
  - pytorch=2.5.1
  - pytorch-mutex=1.0
  - pytz=2025.2
  - pyyaml=6.0.3
  - qt-main=6.7.2
  - qt5compat=6.7.2
  - qt6-main=6.7.2
  - qtbase=6.7.2
  - qtdeclarative=6.7.2
  - qtimageformats=6.7.2
  - qtshadertools=6.7.2
  - qtsvg=6.7.2
  - qttools=6.7.2
  - qttranslations=6.7.2
  - qtwebchannel=6.7.2
  - qtwebsockets=6.7.2
  - rav1e=0.7.1
  - requests=2.32.5
  - sdl2=2.32.56
  - sdl3=3.2.22
  - setuptools=80.9.0
  - shaderc=2025.3
  - sip=6.10.0
  - six=1.17.0
  - snappy=1.2.2
  - spirv-tools=2025.1
  - sqlite=3.50.4
  - svt-av1=3.1.2
  - sympy=1.14.0
  - tbb=2021.13.0
  - tk=8.6.13
  - tomli=2.3.0
  - torchaudio=2.5.1
  - torchvision=0.20.1
  - typing_extensions=4.15.0
  - tzdata=2025b
  - ucrt=10.0.26100.0
  - urllib3=2.5.0
  - vc=14.3
  - vc14_runtime=14.44.35208
  - vcomp14=14.44.35208
  - vs2015_runtime=14.44.35208
  - wheel=0.45.1
  - win_inet_pton=1.1.0
  - x264=1!164.3095
  - x265=3.5
  - xorg-libxau=1.0.11
  - xorg-libxdmcp=1.1.3
  - xz=5.8.1
  - xz-tools=5.8.1
  - yaml=0.2.5
  - zlib=1.3.1
  - zstandard=0.25.0
  - zstd=1.5.7
  - pip:
      - altgraph==0.17.4
      - black==25.9.0
      - chardet==5.2.0
      - click==8.3.0
      - cloc==0.2.5
      - colorama==0.4.6
      - colored==2.3.1
      - gitdb==4.0.12
      - gitpython==3.1.45
      - markdown-it-py==4.0.0
      - mdurl==0.1.2
      - mypy-extensions==1.1.0
      - pathspec==0.12.1
      - pefile==2023.2.7
      - platformdirs==4.5.0
      - pygments==2.19.2
      - pygount==3.1.0
      - pyinstaller==6.16.0
      - pyinstaller-hooks-contrib==2025.9
      - pytokens==0.1.10
      - pywin32-ctypes==0.2.3
      - rich==14.2.0
      - segment-anything==1.0
      - smmap==5.0.2
prefix: C:\Users\takah\anaconda3\envs\maltilabeler-env
